pipeline { 
  agent any 
  satges {
    stage ( " Build" )
    {
      steps {
        sh "npm install node"
            }
    }
  }
  stages {
    stage ("Test")
    {
      steps{
        echo "Tesing is done"
      }
    }
  }
  }
