pipeline {
     agent any
     stages {
      stage ("Build Up"){
        steps {
          sh "npm install node"
        }
      }
      stage("Test"){
        steps{
           ech "Testing Done.."
        }
      }
   }
}
